#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WatchApp.Resource", IsApplication=true)]

namespace WatchApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int generic_confirmation_generic_confirmation_animation = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int generic_confirmation_icon_animation = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int open_on_phone_arrow_animation = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int open_on_phone_path_1_animation = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int open_on_phone_path_2_animation = 2130968580;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f050000
			public const int circular_image_button_anim = 2131034112;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int progress_spinner_sequence = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010039
			public const int action_menu = 2130772025;
			
			// aapt resource value: 0x7f01004b
			public const int bezel_width = 2130772043;
			
			// aapt resource value: 0x7f010019
			public const int buttonRippleColor = 2130771993;
			
			// aapt resource value: 0x7f01005b
			public const int buttonSize = 2130772059;
			
			// aapt resource value: 0x7f01005a
			public const int circleCrop = 2130772058;
			
			// aapt resource value: 0x7f01000f
			public const int circle_border_cap = 2130771983;
			
			// aapt resource value: 0x7f01000e
			public const int circle_border_color = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public const int circle_border_width = 2130771981;
			
			// aapt resource value: 0x7f01000a
			public const int circle_color = 2130771978;
			
			// aapt resource value: 0x7f010010
			public const int circle_padding = 2130771984;
			
			// aapt resource value: 0x7f01000b
			public const int circle_radius = 2130771979;
			
			// aapt resource value: 0x7f010015
			public const int circle_radius_percent = 2130771989;
			
			// aapt resource value: 0x7f01000c
			public const int circle_radius_pressed = 2130771980;
			
			// aapt resource value: 0x7f010016
			public const int circle_radius_pressed_percent = 2130771990;
			
			// aapt resource value: 0x7f01004c
			public const int circular_scrolling_gesture_enabled = 2130772044;
			
			// aapt resource value: 0x7f01005c
			public const int colorScheme = 2130772060;
			
			// aapt resource value: 0x7f010036
			public const int color_sequence = 2130772022;
			
			// aapt resource value: 0x7f010002
			public const int dialogIcon = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int dialogMessage = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int dialogTitle = 2130771968;
			
			// aapt resource value: 0x7f01001f
			public const int dotColor = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int dotColorSelected = 2130772000;
			
			// aapt resource value: 0x7f010024
			public const int dotFadeInDuration = 2130772004;
			
			// aapt resource value: 0x7f010022
			public const int dotFadeOutDelay = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int dotFadeOutDuration = 2130772003;
			
			// aapt resource value: 0x7f010021
			public const int dotFadeWhenIdle = 2130772001;
			
			// aapt resource value: 0x7f01001d
			public const int dotRadius = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int dotRadiusSelected = 2130771998;
			
			// aapt resource value: 0x7f010025
			public const int dotShadowColor = 2130772005;
			
			// aapt resource value: 0x7f010027
			public const int dotShadowDx = 2130772007;
			
			// aapt resource value: 0x7f010028
			public const int dotShadowDy = 2130772008;
			
			// aapt resource value: 0x7f010026
			public const int dotShadowRadius = 2130772006;
			
			// aapt resource value: 0x7f01001c
			public const int dotSpacing = 2130771996;
			
			// aapt resource value: 0x7f010041
			public const int drawer_content = 2130772033;
			
			// aapt resource value: 0x7f01003a
			public const int drawer_title = 2130772026;
			
			// aapt resource value: 0x7f010059
			public const int imageAspectRatio = 2130772057;
			
			// aapt resource value: 0x7f010058
			public const int imageAspectRatioAdjust = 2130772056;
			
			// aapt resource value: 0x7f010018
			public const int imageScaleMode = 2130771992;
			
			// aapt resource value: 0x7f010012
			public const int image_circle_percentage = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int image_horizontal_offcenter_percentage = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int image_tint = 2130771988;
			
			// aapt resource value: 0x7f01005e
			public const int layoutManager = 2130772062;
			
			// aapt resource value: 0x7f010057
			public const int layout_aspectRatio = 2130772055;
			
			// aapt resource value: 0x7f010009
			public const int layout_box = 2130771977;
			
			// aapt resource value: 0x7f010042
			public const int layout_gravityRound = 2130772034;
			
			// aapt resource value: 0x7f01004f
			public const int layout_heightPercent = 2130772047;
			
			// aapt resource value: 0x7f010044
			public const int layout_heightRound = 2130772036;
			
			// aapt resource value: 0x7f010054
			public const int layout_marginBottomPercent = 2130772052;
			
			// aapt resource value: 0x7f010049
			public const int layout_marginBottomRound = 2130772041;
			
			// aapt resource value: 0x7f010056
			public const int layout_marginEndPercent = 2130772054;
			
			// aapt resource value: 0x7f010051
			public const int layout_marginLeftPercent = 2130772049;
			
			// aapt resource value: 0x7f010046
			public const int layout_marginLeftRound = 2130772038;
			
			// aapt resource value: 0x7f010050
			public const int layout_marginPercent = 2130772048;
			
			// aapt resource value: 0x7f010053
			public const int layout_marginRightPercent = 2130772051;
			
			// aapt resource value: 0x7f010048
			public const int layout_marginRightRound = 2130772040;
			
			// aapt resource value: 0x7f010045
			public const int layout_marginRound = 2130772037;
			
			// aapt resource value: 0x7f010055
			public const int layout_marginStartPercent = 2130772053;
			
			// aapt resource value: 0x7f010052
			public const int layout_marginTopPercent = 2130772050;
			
			// aapt resource value: 0x7f010047
			public const int layout_marginTopRound = 2130772039;
			
			// aapt resource value: 0x7f01004e
			public const int layout_widthPercent = 2130772046;
			
			// aapt resource value: 0x7f010043
			public const int layout_widthRound = 2130772035;
			
			// aapt resource value: 0x7f010008
			public const int maxTextSize = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int minTextSize = 2130771975;
			
			// aapt resource value: 0x7f01004a
			public const int navigation_style = 2130772042;
			
			// aapt resource value: 0x7f01003f
			public const int negativeButtonIcon = 2130772031;
			
			// aapt resource value: 0x7f01003e
			public const int neutralButtonIcon = 2130772030;
			
			// aapt resource value: 0x7f01003c
			public const int neutralButtonText = 2130772028;
			
			// aapt resource value: 0x7f01002c
			public const int pageIndicatorDotColor = 2130772012;
			
			// aapt resource value: 0x7f01002d
			public const int pageIndicatorDotColorSelected = 2130772013;
			
			// aapt resource value: 0x7f010031
			public const int pageIndicatorDotFadeInDuration = 2130772017;
			
			// aapt resource value: 0x7f01002f
			public const int pageIndicatorDotFadeOutDelay = 2130772015;
			
			// aapt resource value: 0x7f010030
			public const int pageIndicatorDotFadeOutDuration = 2130772016;
			
			// aapt resource value: 0x7f01002e
			public const int pageIndicatorDotFadeWhenIdle = 2130772014;
			
			// aapt resource value: 0x7f01002a
			public const int pageIndicatorDotRadius = 2130772010;
			
			// aapt resource value: 0x7f01002b
			public const int pageIndicatorDotRadiusSelected = 2130772011;
			
			// aapt resource value: 0x7f010032
			public const int pageIndicatorDotShadowColor = 2130772018;
			
			// aapt resource value: 0x7f010034
			public const int pageIndicatorDotShadowDx = 2130772020;
			
			// aapt resource value: 0x7f010035
			public const int pageIndicatorDotShadowDy = 2130772021;
			
			// aapt resource value: 0x7f010033
			public const int pageIndicatorDotShadowRadius = 2130772019;
			
			// aapt resource value: 0x7f010029
			public const int pageIndicatorDotSpacing = 2130772009;
			
			// aapt resource value: 0x7f010040
			public const int peek_view = 2130772032;
			
			// aapt resource value: 0x7f01003d
			public const int positiveButtonIcon = 2130772029;
			
			// aapt resource value: 0x7f01001a
			public const int pressedButtonTranslationZ = 2130771994;
			
			// aapt resource value: 0x7f010037
			public const int rectLayout = 2130772023;
			
			// aapt resource value: 0x7f010060
			public const int reverseLayout = 2130772064;
			
			// aapt resource value: 0x7f010038
			public const int roundLayout = 2130772024;
			
			// aapt resource value: 0x7f01005d
			public const int scopeUris = 2130772061;
			
			// aapt resource value: 0x7f01004d
			public const int scroll_degrees_per_screen = 2130772045;
			
			// aapt resource value: 0x7f010011
			public const int shadow_width = 2130771985;
			
			// aapt resource value: 0x7f010006
			public const int showDialogWhenTurningOff = 2130771974;
			
			// aapt resource value: 0x7f010005
			public const int showDialogWhenTurningOn = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int showNegativeDialogButton = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int showPositiveDialogButton = 2130771971;
			
			// aapt resource value: 0x7f01003b
			public const int show_overflow_in_peek = 2130772027;
			
			// aapt resource value: 0x7f01005f
			public const int spanCount = 2130772063;
			
			// aapt resource value: 0x7f010017
			public const int square_dimen = 2130771991;
			
			// aapt resource value: 0x7f010061
			public const int stackFromEnd = 2130772065;
			
			// aapt resource value: 0x7f01001b
			public const int update_interval = 2130771995;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080000
			public const int action_choose_expand_selected = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int action_choose_symmetrical_dimen = 2131230721;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090000
			public const int action_button_background = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int ambient_mode_text = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int black = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int black_54p = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int black_86p = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int blue = 2131296261;
			
			// aapt resource value: 0x7f090025
			public const int btn_colored_background_material = 2131296293;
			
			// aapt resource value: 0x7f090026
			public const int button_icon_color = 2131296294;
			
			// aapt resource value: 0x7f090006
			public const int card_default_background = 2131296262;
			
			// aapt resource value: 0x7f090027
			public const int card_grey_text_color = 2131296295;
			
			// aapt resource value: 0x7f090028
			public const int card_text_color = 2131296296;
			
			// aapt resource value: 0x7f090029
			public const int circular_button = 2131296297;
			
			// aapt resource value: 0x7f090007
			public const int circular_button_disabled = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int circular_button_normal = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int circular_button_pressed = 2131296265;
			
			// aapt resource value: 0x7f09002a
			public const int common_google_signin_btn_text_dark = 2131296298;
			
			// aapt resource value: 0x7f09001d
			public const int common_google_signin_btn_text_dark_default = 2131296285;
			
			// aapt resource value: 0x7f09001e
			public const int common_google_signin_btn_text_dark_disabled = 2131296286;
			
			// aapt resource value: 0x7f09001f
			public const int common_google_signin_btn_text_dark_focused = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int common_google_signin_btn_text_dark_pressed = 2131296288;
			
			// aapt resource value: 0x7f09002b
			public const int common_google_signin_btn_text_light = 2131296299;
			
			// aapt resource value: 0x7f090021
			public const int common_google_signin_btn_text_light_default = 2131296289;
			
			// aapt resource value: 0x7f090022
			public const int common_google_signin_btn_text_light_disabled = 2131296290;
			
			// aapt resource value: 0x7f090023
			public const int common_google_signin_btn_text_light_focused = 2131296291;
			
			// aapt resource value: 0x7f090024
			public const int common_google_signin_btn_text_light_pressed = 2131296292;
			
			// aapt resource value: 0x7f09002c
			public const int common_google_signin_btn_tint = 2131296300;
			
			// aapt resource value: 0x7f09000a
			public const int dark_blue = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int dark_grey = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int dark_red = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int dialog_background = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int dialog_shade_background = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int disabled_text_light = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int dismiss_close = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int dismiss_close_pressed = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int dismiss_overlay_bg = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int green = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int grey = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int light_grey = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int orange = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int primary_text_dark = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int primary_text_light = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int red = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int secondary_text_light = 2131296282;
			
			// aapt resource value: 0x7f09001b
			public const int semitransparent_grey = 2131296283;
			
			// aapt resource value: 0x7f09001c
			public const int white = 2131296284;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0000
			public const int action_chooser_base_radius_percent = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int action_chooser_bounce_in_percent = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int action_chooser_icon_height_percent = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int action_chooser_max_radius_percent = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int action_chooser_min_drag_select_percent = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int action_chooser_min_swipe_select_percent = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int action_drawer_expand_icon_top_margin = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int action_drawer_item_bottom_padding = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int action_drawer_item_icon_padding = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int action_drawer_item_icon_right_margin = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int action_drawer_item_icon_size = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int action_drawer_item_text_size = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int action_drawer_item_top_padding = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int action_drawer_peek_top_padding = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int action_drawer_peek_view_height = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int card_content_padding_rect_top = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int circular_button_elevation = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int circular_button_elevation_pressed = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int close_button_diameter = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int confirmation_overlay_image_size = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int confirmation_overlay_text_size = 2131361812;
			
			// aapt resource value: 0x7f0a0015
			public const int diag_button_bottom_padding = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int diag_button_bottom_padding_round = 2131361814;
			
			// aapt resource value: 0x7f0a002f
			public const int diag_button_padding_bottom = 2131361839;
			
			// aapt resource value: 0x7f0a0030
			public const int diag_button_padding_horizontal = 2131361840;
			
			// aapt resource value: 0x7f0a0017
			public const int diag_button_side_padding_right_round = 2131361815;
			
			// aapt resource value: 0x7f0a0031
			public const int diag_button_size = 2131361841;
			
			// aapt resource value: 0x7f0a0018
			public const int diag_content_bottom_padding = 2131361816;
			
			// aapt resource value: 0x7f0a0019
			public const int diag_content_side_padding = 2131361817;
			
			// aapt resource value: 0x7f0a001a
			public const int diag_content_side_padding_round = 2131361818;
			
			// aapt resource value: 0x7f0a001b
			public const int diag_content_top_padding = 2131361819;
			
			// aapt resource value: 0x7f0a001c
			public const int diag_content_top_padding_round = 2131361820;
			
			// aapt resource value: 0x7f0a001d
			public const int diag_floating_height = 2131361821;
			
			// aapt resource value: 0x7f0a0032
			public const int diag_icon_margin_top = 2131361842;
			
			// aapt resource value: 0x7f0a0033
			public const int diag_preferred_padding = 2131361843;
			
			// aapt resource value: 0x7f0a001e
			public const int diag_shade_height_rect = 2131361822;
			
			// aapt resource value: 0x7f0a001f
			public const int diag_shade_height_round = 2131361823;
			
			// aapt resource value: 0x7f0a0020
			public const int dismiss_padding = 2131361824;
			
			// aapt resource value: 0x7f0a0021
			public const int drawer_view_edge_size = 2131361825;
			
			// aapt resource value: 0x7f0a0034
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131361844;
			
			// aapt resource value: 0x7f0a0035
			public const int item_touch_helper_swipe_escape_max_velocity = 2131361845;
			
			// aapt resource value: 0x7f0a0036
			public const int item_touch_helper_swipe_escape_velocity = 2131361846;
			
			// aapt resource value: 0x7f0a0022
			public const int nav_drawer_single_page_circle_radius = 2131361826;
			
			// aapt resource value: 0x7f0a0023
			public const int nav_drawer_single_page_icon_padding = 2131361827;
			
			// aapt resource value: 0x7f0a0024
			public const int nav_drawer_single_page_icon_size = 2131361828;
			
			// aapt resource value: 0x7f0a0025
			public const int nav_drawer_text_size = 2131361829;
			
			// aapt resource value: 0x7f0a0026
			public const int peek_view_bottom_padding = 2131361830;
			
			// aapt resource value: 0x7f0a0027
			public const int peek_view_icon_size = 2131361831;
			
			// aapt resource value: 0x7f0a0028
			public const int peek_view_top_padding = 2131361832;
			
			// aapt resource value: 0x7f0a0029
			public const int screen_percentage_05 = 2131361833;
			
			// aapt resource value: 0x7f0a002a
			public const int screen_percentage_10 = 2131361834;
			
			// aapt resource value: 0x7f0a002b
			public const int screen_percentage_12 = 2131361835;
			
			// aapt resource value: 0x7f0a002c
			public const int screen_percentage_15 = 2131361836;
			
			// aapt resource value: 0x7f0a002d
			public const int wearable_drawer_view_elevation = 2131361837;
			
			// aapt resource value: 0x7f0a002e
			public const int wrv_curve_default_x_offset = 2131361838;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int accept_deny_dialog_negative_bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int accept_deny_dialog_positive_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int action_item_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int action_item_icon_background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int card_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int card_frame = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int card_frame_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int close_button = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_full_open_on_phone = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_dark = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_dark_focused = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_dark_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_dark_normal_background = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_icon_disabled = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_icon_light = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_icon_light_focused = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_icon_light_normal = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_icon_light_normal_background = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_dark_focused = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_dark_normal = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_dark_normal_background = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_disabled = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_text_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_google_signin_btn_text_light_focused = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_google_signin_btn_text_light_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_google_signin_btn_text_light_normal_background = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int generic_confirmation = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int generic_confirmation_animation = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int googleg_disabled_color_18 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int googleg_standard_color_18 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_cc_checkmark = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_cc_clear = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_cc_settings_button_bottom = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_cc_settings_button_center = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_cc_settings_button_e = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_cc_settings_button_top = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_expand_less_white_22 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_expand_more_white_22 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_full_cancel = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_full_sad = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_more_horiz_24dp_wht = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_more_vert_24dp_wht = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Icon = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int open_on_phone = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int open_on_phone_animation = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int preference_wrapped_icon = 2130837550;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Fraction
		{
			
			// aapt resource value: 0x7f0b0000
			public const int action_drawer_item_first_item_top_padding = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int action_drawer_item_last_item_bottom_padding = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int action_drawer_item_left_padding = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int action_drawer_item_right_padding = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int confirmation_overlay_margin_above_text = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int confirmation_overlay_margin_side = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int nav_drawer_margin_2_items = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int nav_drawer_margin_3_items = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int nav_drawer_margin_4_items_horizontal = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public const int nav_drawer_margin_4_items_vertical = 2131427337;
			
			// aapt resource value: 0x7f0b000a
			public const int nav_drawer_margin_5_items_horizontal_middle_row = 2131427338;
			
			// aapt resource value: 0x7f0b000b
			public const int nav_drawer_margin_5_items_horizontal_outer_rows = 2131427339;
			
			// aapt resource value: 0x7f0b000c
			public const int nav_drawer_margin_5_items_vertical = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int nav_drawer_margin_6_items_horizontal = 2131427341;
			
			// aapt resource value: 0x7f0b000e
			public const int nav_drawer_margin_6_items_vertical = 2131427342;
			
			// aapt resource value: 0x7f0b000f
			public const int nav_drawer_margin_7_items_horizontal_middle_row = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public const int nav_drawer_margin_7_items_horizontal_outer_rows = 2131427344;
			
			// aapt resource value: 0x7f0b0011
			public const int nav_drawer_margin_7_items_vertical = 2131427345;
			
			// aapt resource value: 0x7f0b0012
			public const int nav_drawer_text_margin = 2131427346;
			
			static Fraction()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Fraction()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0c001b
			public const int adjust_height = 2131492891;
			
			// aapt resource value: 0x7f0c001c
			public const int adjust_width = 2131492892;
			
			// aapt resource value: 0x7f0c002c
			public const int alertTitle = 2131492908;
			
			// aapt resource value: 0x7f0c0003
			public const int all = 2131492867;
			
			// aapt resource value: 0x7f0c002b
			public const int animatedWrapperContainer = 2131492907;
			
			// aapt resource value: 0x7f0c0020
			public const int auto = 2131492896;
			
			// aapt resource value: 0x7f0c0004
			public const int bottom = 2131492868;
			
			// aapt resource value: 0x7f0c0008
			public const int butt = 2131492872;
			
			// aapt resource value: 0x7f0c0023
			public const int buttonPanel = 2131492899;
			
			// aapt resource value: 0x7f0c000e
			public const int center = 2131492878;
			
			// aapt resource value: 0x7f0c0010
			public const int center_horizontal = 2131492880;
			
			// aapt resource value: 0x7f0c0011
			public const int center_vertical = 2131492881;
			
			// aapt resource value: 0x7f0c0012
			public const int clip_horizontal = 2131492882;
			
			// aapt resource value: 0x7f0c0013
			public const int clip_vertical = 2131492883;
			
			// aapt resource value: 0x7f0c0021
			public const int dark = 2131492897;
			
			// aapt resource value: 0x7f0c002e
			public const int dismiss_overlay_button = 2131492910;
			
			// aapt resource value: 0x7f0c002d
			public const int dismiss_overlay_explain = 2131492909;
			
			// aapt resource value: 0x7f0c0014
			public const int end = 2131492884;
			
			// aapt resource value: 0x7f0c0015
			public const int fill = 2131492885;
			
			// aapt resource value: 0x7f0c0016
			public const int fill_horizontal = 2131492886;
			
			// aapt resource value: 0x7f0c0017
			public const int fill_vertical = 2131492887;
			
			// aapt resource value: 0x7f0c000f
			public const int fit = 2131492879;
			
			// aapt resource value: 0x7f0c000b
			public const int height = 2131492875;
			
			// aapt resource value: 0x7f0c001d
			public const int icon_only = 2131492893;
			
			// aapt resource value: 0x7f0c0002
			public const int item_touch_helper_previous_elevation = 2131492866;
			
			// aapt resource value: 0x7f0c0005
			public const int left = 2131492869;
			
			// aapt resource value: 0x7f0c0022
			public const int light = 2131492898;
			
			// aapt resource value: 0x7f0c0019
			public const int multi_page = 2131492889;
			
			// aapt resource value: 0x7f0c0035
			public const int myButton = 2131492917;
			
			// aapt resource value: 0x7f0c0042
			public const int nested_icon = 2131492930;
			
			// aapt resource value: 0x7f0c000c
			public const int none = 2131492876;
			
			// aapt resource value: 0x7f0c002a
			public const int parentPanel = 2131492906;
			
			// aapt resource value: 0x7f0c0006
			public const int right = 2131492870;
			
			// aapt resource value: 0x7f0c0009
			public const int round = 2131492873;
			
			// aapt resource value: 0x7f0c001a
			public const int single_page = 2131492890;
			
			// aapt resource value: 0x7f0c0024
			public const int spacer = 2131492900;
			
			// aapt resource value: 0x7f0c000a
			public const int square = 2131492874;
			
			// aapt resource value: 0x7f0c001e
			public const int standard = 2131492894;
			
			// aapt resource value: 0x7f0c0018
			public const int start = 2131492888;
			
			// aapt resource value: 0x7f0c003f
			public const int text = 2131492927;
			
			// aapt resource value: 0x7f0c003e
			public const int title = 2131492926;
			
			// aapt resource value: 0x7f0c0007
			public const int top = 2131492871;
			
			// aapt resource value: 0x7f0c002f
			public const int watch_view_stub = 2131492911;
			
			// aapt resource value: 0x7f0c0028
			public const int wearable_support_action_drawer_expand_icon = 2131492904;
			
			// aapt resource value: 0x7f0c0025
			public const int wearable_support_action_drawer_item_icon = 2131492901;
			
			// aapt resource value: 0x7f0c0026
			public const int wearable_support_action_drawer_item_text = 2131492902;
			
			// aapt resource value: 0x7f0c0027
			public const int wearable_support_action_drawer_peek_action_icon = 2131492903;
			
			// aapt resource value: 0x7f0c0029
			public const int wearable_support_action_drawer_title = 2131492905;
			
			// aapt resource value: 0x7f0c0033
			public const int wearable_support_confirmation_overlay_image = 2131492915;
			
			// aapt resource value: 0x7f0c0034
			public const int wearable_support_confirmation_overlay_message = 2131492916;
			
			// aapt resource value: 0x7f0c0040
			public const int wearable_support_drawer_view_peek_container = 2131492928;
			
			// aapt resource value: 0x7f0c0041
			public const int wearable_support_drawer_view_peek_icon = 2131492929;
			
			// aapt resource value: 0x7f0c0036
			public const int wearable_support_nav_drawer_icon_0 = 2131492918;
			
			// aapt resource value: 0x7f0c0038
			public const int wearable_support_nav_drawer_icon_1 = 2131492920;
			
			// aapt resource value: 0x7f0c0039
			public const int wearable_support_nav_drawer_icon_2 = 2131492921;
			
			// aapt resource value: 0x7f0c003a
			public const int wearable_support_nav_drawer_icon_3 = 2131492922;
			
			// aapt resource value: 0x7f0c003b
			public const int wearable_support_nav_drawer_icon_4 = 2131492923;
			
			// aapt resource value: 0x7f0c003c
			public const int wearable_support_nav_drawer_icon_5 = 2131492924;
			
			// aapt resource value: 0x7f0c003d
			public const int wearable_support_nav_drawer_icon_6 = 2131492925;
			
			// aapt resource value: 0x7f0c0037
			public const int wearable_support_nav_drawer_text = 2131492919;
			
			// aapt resource value: 0x7f0c0030
			public const int wearable_support_navigation_drawer_item_icon = 2131492912;
			
			// aapt resource value: 0x7f0c0031
			public const int wearable_support_navigation_drawer_item_text = 2131492913;
			
			// aapt resource value: 0x7f0c0032
			public const int wearable_support_navigation_drawer_page_indicator = 2131492914;
			
			// aapt resource value: 0x7f0c0000
			public const int wearable_support_navigation_drawer_view_pager = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int wearable_support_overlay_confirmation = 2131492865;
			
			// aapt resource value: 0x7f0c001f
			public const int wide = 2131492895;
			
			// aapt resource value: 0x7f0c000d
			public const int width = 2131492877;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0d0000
			public const int action_choose_expand_full_duration = 2131558400;
			
			// aapt resource value: 0x7f0d0001
			public const int action_chooser_anim_duration = 2131558401;
			
			// aapt resource value: 0x7f0d0002
			public const int action_chooser_bounce_delay = 2131558402;
			
			// aapt resource value: 0x7f0d0003
			public const int action_chooser_confirmation_duration = 2131558403;
			
			// aapt resource value: 0x7f0d0004
			public const int google_play_services_version = 2131558404;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Interpolator
		{
			
			// aapt resource value: 0x7f060000
			public const int generic_confirmation_animation_interpolator_0 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int generic_confirmation_animation_interpolator_1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int generic_confirmation_animation_interpolator_2 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int generic_confirmation_animation_interpolator_3 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int open_on_phone_animation_interpolator_0 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int open_on_phone_animation_interpolator_1 = 2131099653;
			
			static Interpolator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Interpolator()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int accept_deny_dialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int action_drawer_item_view = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int action_drawer_peek_view = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int action_drawer_title_view = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int alert_dialog_wearable = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dismiss_overlay = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int navigation_drawer_item_view = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int navigation_drawer_view = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int overlay_confirmation = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int RectangleMain = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int RoundMain = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int single_page_nav_drawer_1_item = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int single_page_nav_drawer_2_item = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int single_page_nav_drawer_3_item = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int single_page_nav_drawer_4_item = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int single_page_nav_drawer_5_item = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int single_page_nav_drawer_6_item = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int single_page_nav_drawer_7_item = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int single_page_nav_drawer_peek_view = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int watch_card_content = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int wearable_drawer_view = 2130903061;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7f0e0000
			public const int time_difference_short_days = 2131623936;
			
			// aapt resource value: 0x7f0e0001
			public const int time_difference_short_hours = 2131623937;
			
			// aapt resource value: 0x7f0e0002
			public const int time_difference_short_minutes = 2131623938;
			
			// aapt resource value: 0x7f0e0003
			public const int time_difference_words_days = 2131623939;
			
			// aapt resource value: 0x7f0e0004
			public const int time_difference_words_hours = 2131623940;
			
			// aapt resource value: 0x7f0e0005
			public const int time_difference_words_minutes = 2131623941;
			
			static Plurals()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Plurals()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0f0034
			public const int app_name = 2131689524;
			
			// aapt resource value: 0x7f0f0000
			public const int buttons_rect_bottom_center = 2131689472;
			
			// aapt resource value: 0x7f0f0001
			public const int buttons_rect_bottom_left = 2131689473;
			
			// aapt resource value: 0x7f0f0002
			public const int buttons_rect_bottom_right = 2131689474;
			
			// aapt resource value: 0x7f0f0003
			public const int buttons_rect_left_bottom = 2131689475;
			
			// aapt resource value: 0x7f0f0004
			public const int buttons_rect_left_center = 2131689476;
			
			// aapt resource value: 0x7f0f0005
			public const int buttons_rect_left_top = 2131689477;
			
			// aapt resource value: 0x7f0f0006
			public const int buttons_rect_right_bottom = 2131689478;
			
			// aapt resource value: 0x7f0f0007
			public const int buttons_rect_right_center = 2131689479;
			
			// aapt resource value: 0x7f0f0008
			public const int buttons_rect_right_top = 2131689480;
			
			// aapt resource value: 0x7f0f0009
			public const int buttons_rect_top_center = 2131689481;
			
			// aapt resource value: 0x7f0f000a
			public const int buttons_rect_top_left = 2131689482;
			
			// aapt resource value: 0x7f0f000b
			public const int buttons_rect_top_right = 2131689483;
			
			// aapt resource value: 0x7f0f000c
			public const int buttons_round_bottom_center = 2131689484;
			
			// aapt resource value: 0x7f0f000d
			public const int buttons_round_bottom_left = 2131689485;
			
			// aapt resource value: 0x7f0f000e
			public const int buttons_round_bottom_left_lower = 2131689486;
			
			// aapt resource value: 0x7f0f000f
			public const int buttons_round_bottom_left_upper = 2131689487;
			
			// aapt resource value: 0x7f0f0010
			public const int buttons_round_bottom_right = 2131689488;
			
			// aapt resource value: 0x7f0f0011
			public const int buttons_round_bottom_right_lower = 2131689489;
			
			// aapt resource value: 0x7f0f0012
			public const int buttons_round_bottom_right_upper = 2131689490;
			
			// aapt resource value: 0x7f0f0013
			public const int buttons_round_center_left = 2131689491;
			
			// aapt resource value: 0x7f0f0014
			public const int buttons_round_center_right = 2131689492;
			
			// aapt resource value: 0x7f0f0015
			public const int buttons_round_top_center = 2131689493;
			
			// aapt resource value: 0x7f0f0016
			public const int buttons_round_top_left = 2131689494;
			
			// aapt resource value: 0x7f0f0017
			public const int buttons_round_top_left_lower = 2131689495;
			
			// aapt resource value: 0x7f0f0018
			public const int buttons_round_top_left_upper = 2131689496;
			
			// aapt resource value: 0x7f0f0019
			public const int buttons_round_top_right = 2131689497;
			
			// aapt resource value: 0x7f0f001a
			public const int buttons_round_top_right_lower = 2131689498;
			
			// aapt resource value: 0x7f0f001b
			public const int buttons_round_top_right_upper = 2131689499;
			
			// aapt resource value: 0x7f0f0023
			public const int common_google_play_services_enable_button = 2131689507;
			
			// aapt resource value: 0x7f0f0024
			public const int common_google_play_services_enable_text = 2131689508;
			
			// aapt resource value: 0x7f0f0025
			public const int common_google_play_services_enable_title = 2131689509;
			
			// aapt resource value: 0x7f0f0026
			public const int common_google_play_services_install_button = 2131689510;
			
			// aapt resource value: 0x7f0f0027
			public const int common_google_play_services_install_text = 2131689511;
			
			// aapt resource value: 0x7f0f0028
			public const int common_google_play_services_install_title = 2131689512;
			
			// aapt resource value: 0x7f0f0029
			public const int common_google_play_services_notification_ticker = 2131689513;
			
			// aapt resource value: 0x7f0f0033
			public const int common_google_play_services_unknown_issue = 2131689523;
			
			// aapt resource value: 0x7f0f002a
			public const int common_google_play_services_unsupported_text = 2131689514;
			
			// aapt resource value: 0x7f0f002b
			public const int common_google_play_services_update_button = 2131689515;
			
			// aapt resource value: 0x7f0f002c
			public const int common_google_play_services_update_text = 2131689516;
			
			// aapt resource value: 0x7f0f002d
			public const int common_google_play_services_update_title = 2131689517;
			
			// aapt resource value: 0x7f0f002e
			public const int common_google_play_services_updating_text = 2131689518;
			
			// aapt resource value: 0x7f0f002f
			public const int common_google_play_services_wear_update_text = 2131689519;
			
			// aapt resource value: 0x7f0f0030
			public const int common_open_on_phone = 2131689520;
			
			// aapt resource value: 0x7f0f0031
			public const int common_signin_button_text = 2131689521;
			
			// aapt resource value: 0x7f0f0032
			public const int common_signin_button_text_long = 2131689522;
			
			// aapt resource value: 0x7f0f001c
			public const int dismiss_overlay_button_label = 2131689500;
			
			// aapt resource value: 0x7f0f001d
			public const int generic_cancel = 2131689501;
			
			// aapt resource value: 0x7f0f001e
			public const int generic_yes = 2131689502;
			
			// aapt resource value: 0x7f0f0036
			public const int hello_rect = 2131689526;
			
			// aapt resource value: 0x7f0f0035
			public const int hello_round = 2131689525;
			
			// aapt resource value: 0x7f0f001f
			public const int navigation_drawer_content_description = 2131689503;
			
			// aapt resource value: 0x7f0f0020
			public const int time_difference_now = 2131689504;
			
			// aapt resource value: 0x7f0f0021
			public const int time_difference_short_days_and_hours = 2131689505;
			
			// aapt resource value: 0x7f0f0022
			public const int time_difference_short_hours_and_minutes = 2131689506;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f100003
			public const int CardText = 2131755011;
			
			// aapt resource value: 0x7f100004
			public const int CardTextBase = 2131755012;
			
			// aapt resource value: 0x7f100005
			public const int CardTitle = 2131755013;
			
			// aapt resource value: 0x7f100006
			public const int CardTitleBase = 2131755014;
			
			// aapt resource value: 0x7f100000
			public const int ConfirmationActivity = 2131755008;
			
			// aapt resource value: 0x7f100007
			public const int DismissOverlayText = 2131755015;
			
			// aapt resource value: 0x7f100008
			public const int DotsPageIndicatorStyle = 2131755016;
			
			// aapt resource value: 0x7f100009
			public const int PageIndicatorViewStyle = 2131755017;
			
			// aapt resource value: 0x7f100001
			public const int SinglePageNavDrawerIconStyle = 2131755009;
			
			// aapt resource value: 0x7f100002
			public const int SinglePageNavDrawerTextStyle = 2131755010;
			
			// aapt resource value: 0x7f100015
			public const int TextAppearance_WearDiag = 2131755029;
			
			// aapt resource value: 0x7f100016
			public const int TextAppearance_WearDiag_Button = 2131755030;
			
			// aapt resource value: 0x7f100017
			public const int TextAppearance_WearDiag_Message = 2131755031;
			
			// aapt resource value: 0x7f100018
			public const int TextAppearance_WearDiag_Title = 2131755032;
			
			// aapt resource value: 0x7f10000a
			public const int TextAppearance_Wearable_Large = 2131755018;
			
			// aapt resource value: 0x7f10000b
			public const int TextAppearance_Wearable_Medium = 2131755019;
			
			// aapt resource value: 0x7f10000c
			public const int TextAppearance_Wearable_Small = 2131755020;
			
			// aapt resource value: 0x7f10000d
			public const int TextView_Large = 2131755021;
			
			// aapt resource value: 0x7f10000e
			public const int TextView_Large_Light = 2131755022;
			
			// aapt resource value: 0x7f10000f
			public const int TextView_Medium = 2131755023;
			
			// aapt resource value: 0x7f100010
			public const int TextView_Medium_Light = 2131755024;
			
			// aapt resource value: 0x7f100011
			public const int TextView_Small = 2131755025;
			
			// aapt resource value: 0x7f100012
			public const int TextView_Small_Light = 2131755026;
			
			// aapt resource value: 0x7f100019
			public const int Theme_WearDiag = 2131755033;
			
			// aapt resource value: 0x7f100013
			public const int Theme_Wearable = 2131755027;
			
			// aapt resource value: 0x7f100014
			public const int Theme_Wearable_Modal = 2131755028;
			
			// aapt resource value: 0x7f10001f
			public const int WearableActionDrawerItemText = 2131755039;
			
			// aapt resource value: 0x7f100020
			public const int WearableActionDrawerTitleText = 2131755040;
			
			// aapt resource value: 0x7f100021
			public const int WearableWatchFaceSettings = 2131755041;
			
			// aapt resource value: 0x7f10001a
			public const int Widget_ActionPage = 2131755034;
			
			// aapt resource value: 0x7f10001b
			public const int Widget_WearDiag_Button = 2131755035;
			
			// aapt resource value: 0x7f10001c
			public const int Widget_WearDiag_TextView = 2131755036;
			
			// aapt resource value: 0x7f10001d
			public const int Widget_WearDiag_TextView_Message = 2131755037;
			
			// aapt resource value: 0x7f10001e
			public const int Widget_WearDiag_TextView_Title = 2131755038;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AcceptDenyDialogPreference = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 2
			public const int AcceptDenyDialogPreference_dialogIcon = 2;
			
			// aapt resource value: 1
			public const int AcceptDenyDialogPreference_dialogMessage = 1;
			
			// aapt resource value: 0
			public const int AcceptDenyDialogPreference_dialogTitle = 0;
			
			// aapt resource value: 4
			public const int AcceptDenyDialogPreference_showNegativeDialogButton = 4;
			
			// aapt resource value: 3
			public const int AcceptDenyDialogPreference_showPositiveDialogButton = 3;
			
			public static int[] AcceptDenySwitchPreference = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 2
			public const int AcceptDenySwitchPreference_dialogIcon = 2;
			
			// aapt resource value: 1
			public const int AcceptDenySwitchPreference_dialogMessage = 1;
			
			// aapt resource value: 0
			public const int AcceptDenySwitchPreference_dialogTitle = 0;
			
			// aapt resource value: 6
			public const int AcceptDenySwitchPreference_showDialogWhenTurningOff = 6;
			
			// aapt resource value: 5
			public const int AcceptDenySwitchPreference_showDialogWhenTurningOn = 5;
			
			// aapt resource value: 4
			public const int AcceptDenySwitchPreference_showNegativeDialogButton = 4;
			
			// aapt resource value: 3
			public const int AcceptDenySwitchPreference_showPositiveDialogButton = 3;
			
			public static int[] ActionLabel = new int[] {
					16842902,
					16842903,
					16842904,
					16842927,
					16843087,
					16843091,
					16843287,
					16843288,
					16843692,
					2130771975,
					2130771976};
			
			// aapt resource value: 8
			public const int ActionLabel_android_fontFamily = 8;
			
			// aapt resource value: 3
			public const int ActionLabel_android_gravity = 3;
			
			// aapt resource value: 6
			public const int ActionLabel_android_lineSpacingExtra = 6;
			
			// aapt resource value: 7
			public const int ActionLabel_android_lineSpacingMultiplier = 7;
			
			// aapt resource value: 5
			public const int ActionLabel_android_maxLines = 5;
			
			// aapt resource value: 4
			public const int ActionLabel_android_text = 4;
			
			// aapt resource value: 2
			public const int ActionLabel_android_textColor = 2;
			
			// aapt resource value: 1
			public const int ActionLabel_android_textStyle = 1;
			
			// aapt resource value: 0
			public const int ActionLabel_android_typeface = 0;
			
			// aapt resource value: 10
			public const int ActionLabel_maxTextSize = 10;
			
			// aapt resource value: 9
			public const int ActionLabel_minTextSize = 9;
			
			public static int[] ActionPage = new int[] {
					16842902,
					16842903,
					16842904,
					16842927,
					16843033,
					16843087,
					16843091,
					16843173,
					16843287,
					16843288,
					16843692,
					16843840,
					16843848,
					2130771975,
					2130771976,
					2130771992,
					2130771993,
					2130771994};
			
			// aapt resource value: 7
			public const int ActionPage_android_color = 7;
			
			// aapt resource value: 11
			public const int ActionPage_android_elevation = 11;
			
			// aapt resource value: 10
			public const int ActionPage_android_fontFamily = 10;
			
			// aapt resource value: 3
			public const int ActionPage_android_gravity = 3;
			
			// aapt resource value: 8
			public const int ActionPage_android_lineSpacingExtra = 8;
			
			// aapt resource value: 9
			public const int ActionPage_android_lineSpacingMultiplier = 9;
			
			// aapt resource value: 6
			public const int ActionPage_android_maxLines = 6;
			
			// aapt resource value: 4
			public const int ActionPage_android_src = 4;
			
			// aapt resource value: 12
			public const int ActionPage_android_stateListAnimator = 12;
			
			// aapt resource value: 5
			public const int ActionPage_android_text = 5;
			
			// aapt resource value: 2
			public const int ActionPage_android_textColor = 2;
			
			// aapt resource value: 1
			public const int ActionPage_android_textStyle = 1;
			
			// aapt resource value: 0
			public const int ActionPage_android_typeface = 0;
			
			// aapt resource value: 16
			public const int ActionPage_buttonRippleColor = 16;
			
			// aapt resource value: 15
			public const int ActionPage_imageScaleMode = 15;
			
			// aapt resource value: 14
			public const int ActionPage_maxTextSize = 14;
			
			// aapt resource value: 13
			public const int ActionPage_minTextSize = 13;
			
			// aapt resource value: 17
			public const int ActionPage_pressedButtonTranslationZ = 17;
			
			public static int[] BoxInsetLayout_Layout = new int[] {
					2130771977};
			
			// aapt resource value: 0
			public const int BoxInsetLayout_Layout_layout_box = 0;
			
			public static int[] CircledImageView = new int[] {
					16843033,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991};
			
			// aapt resource value: 0
			public const int CircledImageView_android_src = 0;
			
			// aapt resource value: 6
			public const int CircledImageView_circle_border_cap = 6;
			
			// aapt resource value: 5
			public const int CircledImageView_circle_border_color = 5;
			
			// aapt resource value: 4
			public const int CircledImageView_circle_border_width = 4;
			
			// aapt resource value: 1
			public const int CircledImageView_circle_color = 1;
			
			// aapt resource value: 7
			public const int CircledImageView_circle_padding = 7;
			
			// aapt resource value: 2
			public const int CircledImageView_circle_radius = 2;
			
			// aapt resource value: 12
			public const int CircledImageView_circle_radius_percent = 12;
			
			// aapt resource value: 3
			public const int CircledImageView_circle_radius_pressed = 3;
			
			// aapt resource value: 13
			public const int CircledImageView_circle_radius_pressed_percent = 13;
			
			// aapt resource value: 9
			public const int CircledImageView_image_circle_percentage = 9;
			
			// aapt resource value: 10
			public const int CircledImageView_image_horizontal_offcenter_percentage = 10;
			
			// aapt resource value: 11
			public const int CircledImageView_image_tint = 11;
			
			// aapt resource value: 8
			public const int CircledImageView_shadow_width = 8;
			
			// aapt resource value: 14
			public const int CircledImageView_square_dimen = 14;
			
			public static int[] CircularButton = new int[] {
					16842981,
					16843033,
					16843173,
					16843840,
					16843848,
					2130771992,
					2130771993,
					2130771994};
			
			// aapt resource value: 0
			public const int CircularButton_android_clickable = 0;
			
			// aapt resource value: 2
			public const int CircularButton_android_color = 2;
			
			// aapt resource value: 3
			public const int CircularButton_android_elevation = 3;
			
			// aapt resource value: 1
			public const int CircularButton_android_src = 1;
			
			// aapt resource value: 4
			public const int CircularButton_android_stateListAnimator = 4;
			
			// aapt resource value: 6
			public const int CircularButton_buttonRippleColor = 6;
			
			// aapt resource value: 5
			public const int CircularButton_imageScaleMode = 5;
			
			// aapt resource value: 7
			public const int CircularButton_pressedButtonTranslationZ = 7;
			
			public static int[] DelayedConfirmationView = new int[] {
					2130771995};
			
			// aapt resource value: 0
			public const int DelayedConfirmationView_update_interval = 0;
			
			public static int[] DotsPageIndicator = new int[] {
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008};
			
			// aapt resource value: 3
			public const int DotsPageIndicator_dotColor = 3;
			
			// aapt resource value: 4
			public const int DotsPageIndicator_dotColorSelected = 4;
			
			// aapt resource value: 8
			public const int DotsPageIndicator_dotFadeInDuration = 8;
			
			// aapt resource value: 6
			public const int DotsPageIndicator_dotFadeOutDelay = 6;
			
			// aapt resource value: 7
			public const int DotsPageIndicator_dotFadeOutDuration = 7;
			
			// aapt resource value: 5
			public const int DotsPageIndicator_dotFadeWhenIdle = 5;
			
			// aapt resource value: 1
			public const int DotsPageIndicator_dotRadius = 1;
			
			// aapt resource value: 2
			public const int DotsPageIndicator_dotRadiusSelected = 2;
			
			// aapt resource value: 9
			public const int DotsPageIndicator_dotShadowColor = 9;
			
			// aapt resource value: 11
			public const int DotsPageIndicator_dotShadowDx = 11;
			
			// aapt resource value: 12
			public const int DotsPageIndicator_dotShadowDy = 12;
			
			// aapt resource value: 10
			public const int DotsPageIndicator_dotShadowRadius = 10;
			
			// aapt resource value: 0
			public const int DotsPageIndicator_dotSpacing = 0;
			
			public static int[] LoadingImageView = new int[] {
					2130772056,
					2130772057,
					2130772058};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] PageIndicatorView = new int[] {
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021};
			
			// aapt resource value: 3
			public const int PageIndicatorView_pageIndicatorDotColor = 3;
			
			// aapt resource value: 4
			public const int PageIndicatorView_pageIndicatorDotColorSelected = 4;
			
			// aapt resource value: 8
			public const int PageIndicatorView_pageIndicatorDotFadeInDuration = 8;
			
			// aapt resource value: 6
			public const int PageIndicatorView_pageIndicatorDotFadeOutDelay = 6;
			
			// aapt resource value: 7
			public const int PageIndicatorView_pageIndicatorDotFadeOutDuration = 7;
			
			// aapt resource value: 5
			public const int PageIndicatorView_pageIndicatorDotFadeWhenIdle = 5;
			
			// aapt resource value: 1
			public const int PageIndicatorView_pageIndicatorDotRadius = 1;
			
			// aapt resource value: 2
			public const int PageIndicatorView_pageIndicatorDotRadiusSelected = 2;
			
			// aapt resource value: 9
			public const int PageIndicatorView_pageIndicatorDotShadowColor = 9;
			
			// aapt resource value: 11
			public const int PageIndicatorView_pageIndicatorDotShadowDx = 11;
			
			// aapt resource value: 12
			public const int PageIndicatorView_pageIndicatorDotShadowDy = 12;
			
			// aapt resource value: 10
			public const int PageIndicatorView_pageIndicatorDotShadowRadius = 10;
			
			// aapt resource value: 0
			public const int PageIndicatorView_pageIndicatorDotSpacing = 0;
			
			public static int[] PercentLayout_Layout = new int[] {
					2130772046,
					2130772047,
					2130772048,
					2130772049,
					2130772050,
					2130772051,
					2130772052,
					2130772053,
					2130772054,
					2130772055};
			
			// aapt resource value: 9
			public const int PercentLayout_Layout_layout_aspectRatio = 9;
			
			// aapt resource value: 1
			public const int PercentLayout_Layout_layout_heightPercent = 1;
			
			// aapt resource value: 6
			public const int PercentLayout_Layout_layout_marginBottomPercent = 6;
			
			// aapt resource value: 8
			public const int PercentLayout_Layout_layout_marginEndPercent = 8;
			
			// aapt resource value: 3
			public const int PercentLayout_Layout_layout_marginLeftPercent = 3;
			
			// aapt resource value: 2
			public const int PercentLayout_Layout_layout_marginPercent = 2;
			
			// aapt resource value: 5
			public const int PercentLayout_Layout_layout_marginRightPercent = 5;
			
			// aapt resource value: 7
			public const int PercentLayout_Layout_layout_marginStartPercent = 7;
			
			// aapt resource value: 4
			public const int PercentLayout_Layout_layout_marginTopPercent = 4;
			
			// aapt resource value: 0
			public const int PercentLayout_Layout_layout_widthPercent = 0;
			
			public static int[] ProgressSpinner = new int[] {
					2130772022};
			
			// aapt resource value: 0
			public const int ProgressSpinner_color_sequence = 0;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130772062,
					2130772063,
					2130772064,
					2130772065};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			public static int[] SignInButton = new int[] {
					2130772059,
					2130772060,
					2130772061};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			public static int[] WatchViewStub = new int[] {
					2130772023,
					2130772024};
			
			// aapt resource value: 0
			public const int WatchViewStub_rectLayout = 0;
			
			// aapt resource value: 1
			public const int WatchViewStub_roundLayout = 1;
			
			public static int[] WearableActionDrawer = new int[] {
					2130772025,
					2130772026,
					2130772027};
			
			// aapt resource value: 0
			public const int WearableActionDrawer_action_menu = 0;
			
			// aapt resource value: 1
			public const int WearableActionDrawer_drawer_title = 1;
			
			// aapt resource value: 2
			public const int WearableActionDrawer_show_overflow_in_peek = 2;
			
			public static int[] WearableDialogPreference = new int[] {
					2130772028,
					2130772029,
					2130772030,
					2130772031};
			
			// aapt resource value: 3
			public const int WearableDialogPreference_negativeButtonIcon = 3;
			
			// aapt resource value: 2
			public const int WearableDialogPreference_neutralButtonIcon = 2;
			
			// aapt resource value: 0
			public const int WearableDialogPreference_neutralButtonText = 0;
			
			// aapt resource value: 1
			public const int WearableDialogPreference_positiveButtonIcon = 1;
			
			public static int[] WearableDrawerView = new int[] {
					2130772032,
					2130772033};
			
			// aapt resource value: 1
			public const int WearableDrawerView_drawer_content = 1;
			
			// aapt resource value: 0
			public const int WearableDrawerView_peek_view = 0;
			
			public static int[] WearableFrameLayout = new int[] {
					16843017,
					16843018,
					16843264,
					16843885,
					2130772034,
					2130772035,
					2130772036,
					2130772037,
					2130772038,
					2130772039,
					2130772040,
					2130772041};
			
			// aapt resource value: 0
			public const int WearableFrameLayout_android_foreground = 0;
			
			// aapt resource value: 2
			public const int WearableFrameLayout_android_foregroundGravity = 2;
			
			// aapt resource value: 3
			public const int WearableFrameLayout_android_foregroundTint = 3;
			
			// aapt resource value: 1
			public const int WearableFrameLayout_android_measureAllChildren = 1;
			
			// aapt resource value: 4
			public const int WearableFrameLayout_layout_gravityRound = 4;
			
			// aapt resource value: 6
			public const int WearableFrameLayout_layout_heightRound = 6;
			
			// aapt resource value: 11
			public const int WearableFrameLayout_layout_marginBottomRound = 11;
			
			// aapt resource value: 8
			public const int WearableFrameLayout_layout_marginLeftRound = 8;
			
			// aapt resource value: 10
			public const int WearableFrameLayout_layout_marginRightRound = 10;
			
			// aapt resource value: 7
			public const int WearableFrameLayout_layout_marginRound = 7;
			
			// aapt resource value: 9
			public const int WearableFrameLayout_layout_marginTopRound = 9;
			
			// aapt resource value: 5
			public const int WearableFrameLayout_layout_widthRound = 5;
			
			public static int[] WearableNavigationDrawer = new int[] {
					2130772042};
			
			// aapt resource value: 0
			public const int WearableNavigationDrawer_navigation_style = 0;
			
			public static int[] WearableRecyclerView = new int[] {
					2130772043,
					2130772044,
					2130772045};
			
			// aapt resource value: 0
			public const int WearableRecyclerView_bezel_width = 0;
			
			// aapt resource value: 1
			public const int WearableRecyclerView_circular_scrolling_gesture_enabled = 1;
			
			// aapt resource value: 2
			public const int WearableRecyclerView_scroll_degrees_per_screen = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
